/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package examsoftware;

import java.awt.BorderLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author zubaeyr
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    int qtype[] = null;
   Copycat copy=new Copycat(this,true);
   String ID;
   String[] examdets;
   static GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices()[0];
 
   public MainFrame(String[] examdets,int[] quetype,String ID) {
        this.ID=ID;
        this.examdets=examdets;
        initComponents();
        setLayout(new BorderLayout());
        add(new XamPanel(ID,examdets[0],Integer.valueOf(examdets[3]).intValue(),Integer.valueOf(examdets[4]).intValue(),examdets[5],quetype,copy));                 
        dispose();
        setUndecorated(true); 
        device.setFullScreenWindow(this);
     // setSize(getToolkit().getScreenSize().width,getToolkit().getScreenSize().height);        
     //  setExtendedState(JFrame.MAXIMIZED_BOTH); 
        
        setAlwaysOnTop(true);
        try{
           setOpacity(0.94f);
        }catch(Exception e){}
       
        
        setVisible(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
   
        this.setVisible(false);        
        Date date=new Date();
        File copyfile=new File("/var/lock/.copied_"+ID+"_"+examdets[0]+"_"+examdets[5]+"_"+date.getDate()+"-"+(date.getMonth()+1)+"-"+(date.getYear()+1900)+".txt");
        try {
            copyfile.createNewFile();
        }catch(Exception e){e.printStackTrace();}
        copy.setVisible(true);
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
